---

- name: Ensure root user has correct settings and password
  become: true
  ansible.builtin.user:
    name: root
    password: >-
      {{ (base_users_master_pass | string | length > 0 and base_users_master_salt | string | length > 0) |
      ternary(base_users_master_pass | password_hash(hashtype='sha512', salt=base_users_master_salt), omit) }}
    shell: /bin/bash
  no_log: '{{ base_users_nolog }}'

- name: Update /root/.bashrc
  become: true
  ansible.builtin.copy:
    src: skel/bashrc.sh
    dest: /root/.bashrc
    owner: root
    group: root
    mode: '0644'
