---

- name: Inspect app ssh private key
  become: true
  ansible.builtin.stat:
    path: /home/{{ apps_app.name }}/.ssh/id_rsa
  register: apps_app_ssh_private_key

- name: Create app account
  become: true
  ansible.builtin.user:
    name: '{{ apps_app.name }}'
    shell: /bin/bash
    generate_ssh_key: "{{ not apps_app_ssh_private_key.stat.exists }}"
    ssh_key_comment: '{{ apps_app.name }}@{{ apps_host_name }}'
    create_home: true

- name: Restrict app home directory
  become: true
  ansible.builtin.file:
    path: /home/{{ apps_app.name }}
    state: directory
    mode: '0750'
    owner: '{{ apps_app.name }}'
    group: '{{ apps_app.name }}'

- name: Add authorized ssh keys
  become: true
  ansible.posix.authorized_key:
    user: '{{ apps_app.name }}'
    key: "{{ lookup('file', apps_deploy_public_key_file) }}"
    state: present
  when: not ansible_check_mode

- name: Grant passwordless sudo to required commands
  become: true
  ansible.builtin.copy:
    content: |
      {{ apps_app.name }} ALL=(ALL) NOPASSWD:/usr/bin/docker,/opt/toolbox/bin/dotenv /home/{{ apps_app.name }}/postgres/*.env *
    dest: /etc/sudoers.d/{{ apps_app.name }}
    owner: root
    group: root
    mode: '0440'
    validate: /usr/sbin/visudo -cf %s

- name: Apply default .bashrc
  become: true
  ansible.builtin.copy:
    src: /etc/skel/.bashrc
    dest: /home/{{ apps_app.name }}/.bashrc
    remote_src: true
    owner: '{{ apps_app.name }}'
    group: '{{ apps_app.name }}'
    mode: '0644'
