---

- name: Create docker overlay networks for each environment
  become: true
  community.docker.docker_network:
    name: '{{ apps_instance.name }}_{{ apps_cluster_realm }}_{{ item.slug }}'
    driver: overlay
    attachable: true
    state: present
  loop: '{{ apps_instance.envs | default([], true) }}'
  loop_control:
    label: '{{ apps_instance.name }}_{{ apps_cluster_realm }}_{{ item.slug }}'
